name: with_me
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.6.0
  fluttertoast: ^3.1.3
  flutter_swiper: ^1.1.6
  dio: ^3.0.4
  flutter_easyrefresh: ^2.0.4
  provider: ^3.2.0
  # 本地存储
  shared_preferences: ^0.5.4+8
  # 加载弹窗
  flutter_spinkit: ^4.1.0
  # 视频播放
  video_player: ^0.10.4
  chewie: ^0.9.8+1
  flutter_html_widget: ^0.0.2
  flutter_ijkplayer: ^0.3.5+1
  fluwx: 1.0.4
  # 开启权限
  permission_handler: ^4.1.0
  # 保存图片
  image_gallery_saver: ^1.2.2
  # 左滑菜单插件
  left_scroll_actions: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/StartBackground.png
   - images/login_image01.png
   - images/login_image02.png
   - images/login_image03.png
   - images/login_image04.png
   - images/login_image05.png
   - images/login_image06.png
   - images/login_image07.png
   - images/1.png
   - images/home_image01.png
   - images/home_image02.png
   - images/home_image03.png
   - images/home_image04.png
   - images/home_image05.png
   - images/home_image06.png
   - images/home_image07.png
   - images/home_image08.png
   - images/home_image09.png
   - images/home_image10.png
   - images/home_image11.png
   - images/home_image12.png
   - images/home_image13.png
   - images/home_image14.png
   - images/home_image15.png
   - images/home_image16.png
   - images/home_image17.png
   - images/home_image18.png
   - images/home_image19.png
   - images/home_image20.png
   - images/home_image21.png
   - images/home_image22.png
   - images/home_image23.png
   - images/home_image24.png
   - images/home_image25.png
   - images/home_image26.png
   - images/home_image28.png
   - images/home_image29.png
   - images/home_image32.png
   - images/home_image33.png
   - images/home_image34.png
   - images/home_image35.png
   - images/home_image36.png
   - images/home_image37.png
   - images/home_image38.png
   - images/home_image39.png
   - images/home_image40.png
   - images/home_image41.png
   - images/home_image42.png
   - images/home_image43.png
   - images/home_image44.png
   - images/home_image45.png
   - images/home_image46.png
   - images/home_image47.png
   - images/home_image48.png
   - images/home_image49.png
   - images/home_image50.png
   - images/home_image51.png
   - images/home_image52.png
   - images/home_image53.png
   - images/home_image54.png
   - images/home_image55.png
   - images/home_image56.png
   - images/home_image57.png
   - images/home_image58.png
   - images/home_image59.png
   - images/home_image60.png
   - images/home_image62.png
   - images/home_image64.png
   - images/home_image65.png
   - images/home_image66.png
   - images/home_image67.png
   - images/home_image68.png
   - images/home_image69.png
   - images/home_image70.png
   - images/home_image71.png
   - images/home_image72.png
   - images/home_image73.png
   - images/home_image74.png
   - images/home_image75.png
   - images/home_image76.png
   - images/home_image77.png
   - images/home_image78.png
   - images/home_image79.png
   - images/home_image80.png
   - images/home_image81.png
   - images/home_image82.png
   - images/home_image83.png
   - images/home_image84.png
   - images/home_image85.png
   - images/home_image86.png
   - images/home_image87.png
   - images/home_image88.png
   - images/home_image89.png
   - images/home_image90.png
   - images/home_image91.png
   - images/home_image92.png
   - images/home_image93.png
   - images/home_image94.png
   - images/home_image95.png
   - images/home_image96.png
   - images/home_image97.png
   - images/home_image98.png
   - images/Lack_image01.png
   - images/close_image30.png
   - images/close_image31.png
   - images/kuajinggonglve_image27.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
